backend:
  name: github
  repo: caseykey/caseykey.github.io
  branch: source
  site_domain: quirky-bassi-7f760a.netlify.com

media_folder: "images/uploads"

collections:
  - label: "Projects" # Used in the UI
    name: "projects" # Used in routes, e.g., /admin/collections/blog
    folder: "src/data/projects" # The path to the file where projects are defined
    create: true
    extension: json
    format: json
    fields: # The fields for each document, usually in front matter
      - {label: "Project Name", name: "project", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - label: "Icons"
        name: "icons"
        widget: "object"
        fields:
          - {label: "Font Awesome", name: "fa", widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
          - {label: "Devicons", name: "di", widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
          - {label: "Ionicons", name: "io", widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string"}
